# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Producto Disponible'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, height_field='29', upload_to='productos/%d/%m/%Y', width_field='29'),
        ),
    ]
