# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_auto_20160914_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='url_height',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='url_width',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='productos/%d/%m/%Y'),
        ),
    ]
