# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_auto_20160914_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='productos/%Y/%m/%d'),
        ),
    ]
