# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_auto_20160914_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', stdimage.models.StdImageField(blank=True, upload_to='slider/%Y/%m/%d')),
            ],
        ),
    ]
